### ISSUE TITLE
[Suggestion] - Disable thick_bridges

### ISSUE THREAD

**Issue by eMPai-git** [DrLex0/FFCP-GCodeSnippets#21]
**Description**

Since PrusaSlicer 2.4.0 there is a new bridging method, similar to other slicers. See description in the [PrusaSlicer 2.4.0-alpha1](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.4.0-alpha1) release notes. By using older configs in 2.4.0 `thick_bridges` are enabled by default, which is the old Slic3r behavior.

I had great success using the new bridging method with PLA by disabling `thick_bridges` in the settings.
I propose to disable `thick_bridges` at least for PLA configs.

**Environment**

I am using an unmodified Flashforge Creator Pro.

**Comment by DrLex0** [comment]
Thick bridges are now disabled for the profiles where it makes sense.
