### ISSUE TITLE
Slicing fails with "variable does not exist" error

### ISSUE THREAD

**Issue by Meganium97** [DrLex0/FFCP-GCodeSnippets#23]
**Describe the bug**

Provide a clear and concise description of the bug here.
Using SuperSlicer with "import PrusaSlicer bundle" method, slicing fails with unknown variable error
`Parsing error at line 98: Variable does not exist
;cooling enabled = [cooling]
                    ^`
**Environment**
Garuda Linux, using superslicer-prerelease-bin from the aur., Using latest gpx via aur and git, perl version 5.36.0
Include the following things:
* Your OS and the version of PrusaSlicer the issue is encountered with.
  Mind that bugs with alpha releases of PrusaSlicer should probably not be filed. Wait at least until the next beta release.
* The version of your GPX binary (try `gpx -?`)
* The version of your Perl runtime (try `perl --version`), and if Windows, what kind of runtime (Strawberry Perl, Cygwin, or through WSL).

**To Reproduce**
Slice Anything. Error pops up on Dualstrusion setup, other setups produce absolutely nothing.
By far the most useful thing you can provide, is a PrusaSlicer project file (3MF) that demonstrates the problem: use “Save Project” in the File menu. If possible, also include both the final .gcode and .x3g files. You can package everything into one ZIP file.

* If specific steps are required to reproduce the behavior, list them here.

**Comment by DrLex0** [comment]
Quote from the README:
> These configs and G-code are made specifically for PrusaSlicer. They might work in the original Slic3r from which PrusaSlicer was forked, but I give no guarantees, and I give no support if you use this with anything else than PrusaSlicer.
