### ISSUE TITLE
How do I thank you

### ISSUE THREAD

**Issue by PeterGarrone** [DrLex0/FFCP-GCodeSnippets#25]
I owe you my sanity. I imported a release from 2018 into Slic3r, and my ASA started working and my PLA stopped collapsing. A vast feeling of relaxation ensued.

**Comment by DrLex0** [comment]
If you really want to send something as a thanks, there are some [donation options](https://www.dr-lex.be/about/#contact) on my site. Otherwise, you can simply close this issue and consider me thanked :)

**Comment by PeterGarrone** [comment]
Donated $100 Australian. Cheers.
